Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/focal64"

  config.vm.provider "virtualbox" do |vb|
    vb.memory = "1024"
    vb.cpus = 1
  end

  config.vm.define "server" do |server|
    server.vm.network "public_network", ip: "192.168.1.100"
    server.vm.hostname = "server"
  end

  config.vm.define "client" do |client|
    client.vm.network "public_network", ip: "192.168.1.101"
    client.vm.hostname = "client"
  end
end